#!/bin/bash

tfwi_usage() {
	cat >&2 <<EOF
To get work item completions and listings using $0, add the following lines to
your .bashrc:

export TFWI_COLLECTION=http://your-tfs-server:8080/tfs/YourCollection
export TFWI_PROJECT=YourTFSProject
export TFWI_QUERY="Query name to use"

# and optionally:

export TFWI_FORMAT="[%(id)s] %(title)s"
EOF
	exit 1
}

if [[ $1 ]]; then
	exec git tf checkin --no-lock --no-metadata --shallow --associate "$@"
else
	if [[ -z $TFWI_COLLECTION ||
		-z $TFWI_PROJECT ||
		-z $TFWI_QUERY ]]; then
		tfwi_usage
	fi

	if tput cols &> /dev/null; then
		cols="-w $(tput cols)"
	fi

	exec tfwi --collection="$TFWI_COLLECTION" \
		--project="$TFWI_PROJECT" \
		--format="${TFWI_FORMAT:-[%(id)s] %(title)s}" \
		"$TFWI_QUERY" | fribidi --ltr $cols
fi

